### ISSUE TITLE
scrollTo not working

### ISSUE THREAD

**Issue by Schantanu** [gfranko/jquery.tocify.js#106]
I have a Navbar that covers up the selected table of contents title. I tried making modifications to the scrollTo value but fail to see it working. What is the write way to achieve an offset from the top of the page, so that the selection and title are aligned?

![](https://user-images.githubusercontent.com/7819582/38588217-5a2ab6e0-3cea-11e8-9f73-cff40f8dabaf.PNG)

**Comment by seweil** [comment]
I've done this by scrolling the content, not the entire page.
Sample here with minimal delta from base Slate: https://github.com/seweil/slate-test
And in production here: http://smartsheet-platform.github.io/api-docs/

One unresolved bug: Browser back button doesn't work well. I'd appreciate suggestions here.

(The quick and dirty solution is to add a lot of padding before each header.)

**Comment by Schantanu** [comment]
Hi @seweil , I am trying to achieve exactly that. The Navbar is in position: fixed, and hence hiding the page content. What parameter did you use to scroll the content from the tocify jquery?

**Comment by seweil** [comment]
You'll will have to look at the code changes in this fork

**Comment by Schantanu** [comment]
Alright, I got it to work. I added the intended value in pixel (e.g. 70) on line 968.

      // _scrollTo
      // ---------
      //      Scrolls to a specific element
      _scrollTo: function(elem) {

        var self = this,
          duration = self.options.smoothScroll || 0,
          scrollTo = self.options.scrollTo + 70,
          currentDiv = $('div[data-unique="' + elem.attr("data-unique") + '"]');

        if (!currentDiv.length) {

          return self;

        }

I am not sure why this works, but inserting the value in the scrollTo parameter itself on line 88 does not.
