### ISSUE TITLE
toc is not generated: 'selectors': 'h2,h3,h4,h5', post only have ‘h3’

### ISSUE THREAD

**Issue by HereChen** [gfranko/jquery.tocify.js#87]
My article only have h3 tag, and I set  'selectors': 'h2,h3,h4,h5', toc is not generated in this situation.

Do the article must have the h2 tag ?
##

**Comment by choaklin** [comment]
'selectors' start with 'h3'

**Comment by HereChen** [comment]
> 
> 
> 'selectors' start with 'h3'

Ok. Thanks.
