### ISSUE TITLE
这个插件都没人维护了，没人再写一个更加方便的目录生成器吗？

### ISSUE THREAD

**Issue by ztmsimon** [gfranko/jquery.tocify.js#97]
这个插件说明太少了，按官方的说明都没办法实现官方一样的效果。
没人再写一个更加方便的目录生成器吗？

**Comment by li-xinyang** [comment]
你写也呀，你以为 GitHub 是免费应用商店吗？

You can do it yourself. Do you really think GitHub is a free app store?
